//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.14 at 03:51:18 PM CEST 
//


package com.github.lindenb.xml4ngs.entities;

import java.io.File;

import javax.xml.stream.XMLStreamException;
import javax.xml.stream.XMLStreamWriter;



public class Fastq extends AbstractHasProperties
	{
    private int index=-1;
    private File path=null;

    /**
     * Gets the value of the index property.
     * 
     */
    public int getIndex() {
        return index;
    }

    /**
     * Sets the value of the index property.
     * 
     */
    public void setIndex(int value) {
    	if(!(value==1 || value==2)) throw new IllegalArgumentException();
        this.index = value;
    }

    /**
     * Gets the value of the path property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public File  getPath() {
        return path;
    }

    /**
     * Sets the value of the path property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPath(File value) {
        this.path = value;
    }
    
  private Pair owner;
  
  public Pair getPair()
  	{
  	return this.owner;
  	}
  
  public void setPair(Pair owner)
  	{
  	this.owner=owner;
  	}
  
  @Override
public AbstractHasProperties getParentProperties()
	{
	return getPair();
	}
  
  @Override
  public String toString()
  	{
  	return getPath().getPath();
  	}
  
  public void write(XMLStreamWriter w) throws XMLStreamException
	{
	 if(!properties.isEmpty())
		 {
		 w.writeStartElement("fastq");
		 properties.write(w, null);
		 }
	 else
		 {
		 w.writeEmptyElement("fastq");
		 }
	
	 w.writeAttribute("index",String.valueOf(getIndex()));
	 w.writeAttribute("path",getPath().getPath());
	 
	 if(!properties.isEmpty())
		 {
		 w.writeEndElement();
		 }
	 }

  
}
